### ISSUE TITLE
bad python loader line in tray_icon.plugin

### ISSUE THREAD

**Issue by pguridi** [palfrey/rhythmbox-tray-icon#14]
Plugin fails to load in rhythmbox 3.01, (fedora 20, x64).

(rhythmbox:6344): libpeas-WARNING **: Could not find loader 'python' for plugin 'tray_icon'

changing the line loader line to: Loader=python3, in tray_icon.plugin, fixes it.

**Comment by palfrey** [comment]
Fixed by https://github.com/palfrey/rhythmbox-tray-icon/pull/16
