### ISSUE TITLE
Tray Icon right click -> Quit non functional on XFCE/Xubuntu

### ISSUE THREAD

**Issue by aguenther** [palfrey/rhythmbox-tray-icon#7]
If I start Rhytmbox through the shell, clicking Quit in the tray icon's popup menu causes:

(rhythmbox:17683): Gtk-CRITICAL **: gtk_main_quit: assertion `main_loops != NULL' failed

nothing other happens. The only way to quit rhytmbox is via Music->Quit or Ctrl+Q

**Comment by mostafaasadi** [comment]
Hi 
this bug effect me too

**Comment by palfrey** [comment]
Is this still present on recent versions of Xfce? I'm not able to reproduce in it in a more conventional Gnome environment

**Comment by palfrey** [comment]
Closing for the moment. Please re-open if you're able to reproduce it.
